# Generated by Django 5.0.6 on 2024-07-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_image',
            field=models.CharField(default='https://static.vecteezy.com/system/resources/thumbnails/001/826/199/small_2x/progress-loading-bar-buffering-download-upload-and-loading-icon-vector.jpg', max_length=5000),
        ),
    ]
